### ISSUE TITLE
Some thoughts and questions

### ISSUE THREAD

**Issue by londoh** [whois-server-list/whois-server-list#1]
Hi

First off: Thank you for this compiling this list

I have used phpwhois and a script by Ben Okopnik in private projects for some years - and I have to (shamefully) say without much thought as to what goes on behind them. But its obvious they are in need of some updates which arent happening.

And so I came to researching other options and found your list.

Despite some experience of web dev and inter-net-working I never quite grasped the hassle caused because there is no standardised format for whois.  I am astounded at this and dont understand why its never been corralled by an rfc or similar.

I notice around github you have been asking others to combine efforts to compile a list of servers which imho under the circumstances has to be a good thing.

Do you think your script will become the "standard list"
Do you think xml is the right format?
Do you have any pointers or thoughts re. parsing whois output?

Regards

l

**Comment by malkusch** [comment]
> Do you think your script will become the "standard list"

I can't predict that. But at the current time I didn't receive so much acceptance from the other projects around. So it looks like everybody wants to brew his own soup. Therefore I just consume those soups and present you this compiled soup.

> Do you think xml is the right format?

I do. It's a perfectly mature interoperable format and I do believe unmarshaller are available in any language. But if you think there's a better format I'm listening. Also I'm open for changing the schema as well.

> Do you have any pointers or thoughts re. parsing whois output?

Not really. And to be honest at current time I don't care much about that. The only information I do care is checking the availability of a domain. But if parsing the other informations would become interesting I'd define antlr grammars similar to [the one I use currently for IANA's whois server](https://github.com/whois-server-list/whois-server-list-maven-plugin/blob/master/src/main/antlr4/de/malkusch/whoisServerList/compiler/list/iana/IanaWhois.g4).

I'll close that issue as I don't see any issue here.
